"""add matched_activity_id to planned_workouts

Revision ID: 034472f35c84
Revises: 2dbc764cb2f6
Create Date: 2026-07-17 11:53:39.110050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '034472f35c84'
down_revision: Union[str, Sequence[str], None] = '2dbc764cb2f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planned_workouts', sa.Column('matched_activity_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'planned_workouts', 'activities', ['matched_activity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planned_workouts', type_='foreignkey')
    op.drop_column('planned_workouts', 'matched_activity_id')
    # ### end Alembic commands ###
