"""add is_reusable to workout_templates

Revision ID: 2dbc764cb2f6
Revises: 3bb3b6d6d043
Create Date: 2026-07-17 07:19:42.831080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dbc764cb2f6'
down_revision: Union[str, Sequence[str], None] = '3bb3b6d6d043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_templates', sa.Column('is_reusable', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_templates', 'is_reusable')
    # ### end Alembic commands ###
