"""add hr zone minutes to activities

Revision ID: 3bb3b6d6d043
Revises: 9eea66f3a625
Create Date: 2026-07-16 16:41:33.792668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bb3b6d6d043'
down_revision: Union[str, Sequence[str], None] = '9eea66f3a625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('z1_min', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('z2_min', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('z3_min', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('z4_min', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('z5_min', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('below_z1_min', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'below_z1_min')
    op.drop_column('activities', 'z5_min')
    op.drop_column('activities', 'z4_min')
    op.drop_column('activities', 'z3_min')
    op.drop_column('activities', 'z2_min')
    op.drop_column('activities', 'z1_min')
    # ### end Alembic commands ###
