"""initial schema

Revision ID: e33a90cc0bb3
Revises: 
Create Date: 2026-07-15 07:43:52.127942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e33a90cc0bb3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('strava_athlete_id', sa.BigInteger(), nullable=False),
    sa.Column('strava_access_token', sa.String(length=255), nullable=True),
    sa.Column('strava_refresh_token', sa.String(length=255), nullable=True),
    sa.Column('strava_expires_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('fc_max', sa.Integer(), nullable=True),
    sa.Column('pr_5k_sec', sa.Integer(), nullable=True),
    sa.Column('pr_10k_sec', sa.Integer(), nullable=True),
    sa.Column('pr_semi_sec', sa.Integer(), nullable=True),
    sa.Column('pr_marathon_sec', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('strava_athlete_id')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strava_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('sport_type', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('duration_min', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Float(), nullable=True),
    sa.Column('total_elevation', sa.Float(), nullable=True),
    sa.Column('charge_load', sa.Float(), nullable=True),
    sa.Column('hr_data', sa.Text(), nullable=True),
    sa.Column('velocity_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strava_id')
    )
    op.create_table('prep_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('race_type', sa.String(length=50), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('goal_time', sa.String(length=20), nullable=True),
    sa.Column('sessions_per_week', sa.Integer(), nullable=False),
    sa.Column('cross_sports', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('fitness_level', sa.String(length=20), nullable=True),
    sa.Column('contexte', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sport_type', sa.String(length=100), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('zone', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planned_workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('week_start', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('strava_activity_id', sa.BigInteger(), nullable=True),
    sa.Column('custom_name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prep_weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=True),
    sa.Column('week_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_load', sa.Float(), nullable=True),
    sa.Column('actual_load', sa.Float(), nullable=True),
    sa.Column('imported', sa.Boolean(), nullable=True),
    sa.Column('bloc', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['prep_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prep_weeks')
    op.drop_table('planned_workouts')
    op.drop_table('workout_templates')
    op.drop_table('prep_plans')
    op.drop_table('activities')
    op.drop_table('users')
    # ### end Alembic commands ###
